server: irc.afternet.org  # The server to connect to.
nick: jamician  # The bot's nickname.
prefix: '!'  # All commands will begin with this prefix.


client:  # Options passed to the IRC client.
  channels: ['#alakajam']
  autoConnect: true
  userName: Jamician
  realName: Alakajam.com bot, AKA "Jamician"


admin:  # Administration config.
  users: []  # A list of friendly IRC users.
  blockList: []  # A list of mean IRC users.
  password: muffins  # A strong password.


api:  # API endpoints, listed by command.
  timeleft: &featuredEvent 'https://alakajam.com/api/featuredEvent'
  panic: *featuredEvent
  random: *featuredEvent
  find: 'https://alakajam.com/api/user/{{user}}/latestEntry'


commands:
  panic:
    messages:
      - "Just {{time}} left. Get a move on!"
      - "{{time}} to get your asses in gear!"
      - "Come on, you can do it! {{time}} left!"
      - "{{time}} left to perfect your masterpiece!"
      - "{{time}} left. PANIC! \:D/"
      - "Dreams will be crushed in {{time}} and counting."
  random:
    pending: "{{event.title}} has not started yet"
    empty: "No entries for {{event.title}}"
    entry: "Random entry for {{event.title|safe}}: '{{entry.title|safe}}' by{% set sep = joiner() %}{% for user in entry.users %}{{sep()}} {{user.title|safe}}{% endfor %}  https://alakajam.com/{{entry.event_name}}/{{entry.id}}"
